name: Build conda packages

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.11"]
    steps:
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: List Visual Studio versions
        run: vswhere -latest -format json
      - uses: actions/checkout@v4
      - name: update submodules
        #       shell: bash -l {0}
        run: |
          git submodule update --init --recursive
      - name: test build
        run: |
           pip install .
      - name: Conda build
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN  }}
        shell: bash -l {0}
        run: |
          conda install -c conda-forge conda-build scikit-build-core numpy cython anaconda-client conda-libmamba-solver -y
          conda build -c conda-forge -c loop3d --output-folder conda conda  --python ${{matrix.python-version}}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conda-build-${{ matrix.python-version }}
          path: conda
